package com.example.musicplayerdome.db;


import com.example.musicplayerdome.main.bean.DRGreenDaoBean;
import com.example.musicplayerdome.search.bean.SearchHistoryBean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dRGreenDaoBeanDaoConfig;
    private final DaoConfig searchHistoryBeanDaoConfig;

    private final DRGreenDaoBeanDao dRGreenDaoBeanDao;
    private final SearchHistoryBeanDao searchHistoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dRGreenDaoBeanDaoConfig = daoConfigMap.get(DRGreenDaoBeanDao.class).clone();
        dRGreenDaoBeanDaoConfig.initIdentityScope(type);

        searchHistoryBeanDaoConfig = daoConfigMap.get(SearchHistoryBeanDao.class).clone();
        searchHistoryBeanDaoConfig.initIdentityScope(type);

        dRGreenDaoBeanDao = new DRGreenDaoBeanDao(dRGreenDaoBeanDaoConfig, this);
        searchHistoryBeanDao = new SearchHistoryBeanDao(searchHistoryBeanDaoConfig, this);

        registerDao(DRGreenDaoBean.class, dRGreenDaoBeanDao);
        registerDao(SearchHistoryBean.class, searchHistoryBeanDao);
    }
    
    public void clear() {
        dRGreenDaoBeanDaoConfig.clearIdentityScope();
        searchHistoryBeanDaoConfig.clearIdentityScope();
    }

    public DRGreenDaoBeanDao getDRGreenDaoBeanDao() {
        return dRGreenDaoBeanDao;
    }

    public SearchHistoryBeanDao getSearchHistoryBeanDao() {
        return searchHistoryBeanDao;
    }

}
